### ISSUE TITLE
Wallpaper Transform support?

### ISSUE THREAD

**Issue by blandman** [rweichler/cylinder#61]
Hello,

Thanks for this awesome utility, discovered it today and have been experimenting with lua and love using the animations.

This is more of a question opposed to an issue.
I was curious if there is a way to animate the wallpaper behind the icons within Lua for custom speed or effects. My vision is the wallpaper would translate at half speed with the pages, like a panorama parallax effect.

Thank you for your time

**Comment by rweichler** [comment]
There's already a tweak called Parallax that does this: https://www.youtube.com/watch?v=JxFhPuUvjAQ

Unless if there is a compelling reason to, I am not planning on adding a Lua binding for custom wallpaper scrolling. It wouldn't really make that much sense in my opinion since it's usually just "make it scroll faster than the icons or slower", which you could just use a slider with a few lines of code, instead of creating a bunch of bindings and using Lua for the same exact effect basically.

**Comment by blandman** [comment]
Thank you for your quick response. 
I have tried the parallax tweak and unfortunately it is not compatible with anything past iOS 6. 
I am very intrigued to the idea of a slider with a few lines of code. I'll do some googling and see what I can turn up, maybe take the opportunity to upload a parallax tweak that works with iOS 8.

**Comment by rweichler** [comment]
Sounds good :)
